---
title: "dissertation_rmd_main_2018_2019"
author: "Michael Guzzardi"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# install.packages("gt")
# install.packages("dplyr")
```

```{r include=FALSE}
library(tidyverse)
library(fixest)
library(lubridate)
library(ggplot2)
library(readr)
library(sf)
library(rgdal)
library(tmap)
library(gridExtra)
library(dplyr)
library(gt)
library(modelsummary)
```

### Treat and Control Comparisons/PTA check

```{r include=FALSE}
setwd("/Users/michaelguzzardi/Desktop/LSE/Dissertation/Data/indego/")

#import data indego
indego_trips_2018q1  <- read_csv('indego-trips-2018-q1.csv') %>%
  mutate(bike_type='standard') #TODO: double check they didn't have electric bikes in 1H 2018
indego_trips_2018q2  <- read_csv('indego-trips-2018-q2.csv') %>%
  mutate(bike_type='standard') #double check
indego_trips_2018q3  <- read_csv('indego-trips-2018-q3.csv')
indego_trips_2018q4  <- read_csv('indego-trips-2018-q4.csv')

indego_trips_2019q1  <- read_csv('indego-trips-2019-q1.csv')
indego_trips_2019q2  <- read_csv('indego-trips-2019-q2.csv')
indego_trips_2019q3  <- read_csv('indego-trips-2019-q3.csv')
indego_trips_2019q4  <- read_csv('indego-trips-2019-q4.csv')

#subset data
indego_trips_2018q1 <- subset(indego_trips_2018q1, select=c(start_time, passholder_type, bike_type))
indego_trips_2018q2 <- subset(indego_trips_2018q2, select=c(start_time, passholder_type, bike_type))
indego_trips_2018q3 <- subset(indego_trips_2018q3, select=c(start_time, passholder_type, bike_type))
indego_trips_2018q4 <- subset(indego_trips_2018q4, select=c(start_time, passholder_type, bike_type))


indego_trips_2019q1 <- subset(indego_trips_2019q1, select=c(start_time, passholder_type, bike_type))
indego_trips_2019q2 <- subset(indego_trips_2019q2, select=c(start_time, passholder_type, bike_type))
indego_trips_2019q3 <- subset(indego_trips_2019q3, select=c(start_time, passholder_type, bike_type)) %>%
  mutate(start_time=as.Date(start_time,'%m/%d/%Y'))
indego_trips_2019q4 <- subset(indego_trips_2019q4, select=c(start_time, passholder_type, bike_type))

#bind into one dataset
indego_trips_all <- rbind(indego_trips_2018q1, indego_trips_2018q2, indego_trips_2018q3, indego_trips_2018q4, indego_trips_2019q1,indego_trips_2019q2,indego_trips_2019q3,indego_trips_2019q4)
indego_trips_all <- dplyr::rename(indego_trips_all,usertype=passholder_type)

#filter out ebikes (see indego ebike analysis script for portion of ebikes filtered out)
indego_trips_all <- indego_trips_all %>%
  filter(bike_type != 'electric') %>%
  select(-bike_type) #remove bike_type column

#round start time dates to the nearest day and month for agg purposes
indego_trips_all <- indego_trips_all %>%
  mutate(start_time_day=trunc(start_time, unit='days')) %>%
  mutate(start_time_month=trunc(start_time, unit='months')) %>%
  mutate(week_num=strftime(start_time_day, format='%V')) %>% #average by week to smooth chart
  mutate(year=strftime(start_time_day, format='%Y')) %>%
  mutate(year_month_week=strftime(start_time_day, format='%Y-%m-%V'))



#filter to day passes and walk-ups
indego_trips_non_member <- indego_trips_all %>%
  filter(usertype %in% c('Day Pass','Walk-up')) %>%
  mutate(non_member = 1) #add indicator variable for non_member status

#filter to year memberships
indego_trips_member <- indego_trips_all %>%
  filter(usertype %in% c('Indego365')) %>%
  mutate(non_member = 0)

# #agg by day and count all
# indego_trips_all_by_day <- indego_trips_all %>%
#   count(start_time_day)
# 
# #agg non_member by day and count
# indego_trips_non_member_by_day <- indego_trips_non_member %>%
#   count(start_time_day)
# 
# #agg member by day and count
# indego_trips_member_by_day <- indego_trips_member %>%
#   count(start_time_day)

#agg by week and count all
indego_trips_all_by_week <- indego_trips_all %>%
  dplyr::count(year_month_week)

#agg by week and count non members
indego_trips_non_member_by_week<- indego_trips_non_member %>%
  dplyr::count(year_month_week)

#agg by week and count members
indego_trips_member_by_week <- indego_trips_member %>%
  dplyr::count(year_month_week)

```

```{r include=FALSE}
setwd("/Users/michaelguzzardi/Desktop/LSE/Dissertation/Data/citi_bike/")

#import data csvs citi bike nyc
cb_trips_201801  <- read_csv('201801-citibike-tripdata.csv')
cb_trips_201802  <- read_csv('201802-citibike-tripdata.csv')
cb_trips_201803  <- read_csv('201803-citibike-tripdata.csv')
cb_trips_201804  <- read_csv('201804-citibike-tripdata.csv')
cb_trips_201805  <- read_csv('201805-citibike-tripdata.csv')
cb_trips_201806  <- read_csv('201806-citibike-tripdata.csv')
cb_trips_201807  <- read_csv('201807-citibike-tripdata.csv')
cb_trips_201808  <- read_csv('201808-citibike-tripdata.csv')
cb_trips_201809  <- read_csv('201809-citibike-tripdata.csv')
cb_trips_201810  <- read_csv('201810-citibike-tripdata.csv')
cb_trips_201811  <- read_csv('201811-citibike-tripdata.csv')
cb_trips_201812  <- read_csv('201812-citibike-tripdata.csv')



cb_trips_201901  <- read_csv('201901-citibike-tripdata.csv')
cb_trips_201902  <- read_csv('201902-citibike-tripdata.csv')
cb_trips_201903  <- read_csv('201903-citibike-tripdata.csv')
cb_trips_201904  <- read_csv('201904-citibike-tripdata.csv')
cb_trips_201905  <- read_csv('201905-citibike-tripdata.csv')
cb_trips_201906  <- read_csv('201906-citibike-tripdata.csv')
cb_trips_201907  <- read_csv('201907-citibike-tripdata.csv')
cb_trips_201908  <- read_csv('201908-citibike-tripdata.csv')
cb_trips_201909  <- read_csv('201909-citibike-tripdata.csv')
cb_trips_201910  <- read_csv('201910-citibike-tripdata.csv')
cb_trips_201911  <- read_csv('201911-citibike-tripdata.csv')
cb_trips_201912  <- read_csv('201912-citibike-tripdata.csv')

#select only start time from each df
cb_trips_201801 <- cb_trips_201801 %>%
  subset(select=c(starttime, usertype))

cb_trips_201802 <- cb_trips_201802 %>%
  subset(select=c(starttime, usertype))

cb_trips_201803 <- cb_trips_201803 %>%
  subset(select=c(starttime, usertype))

cb_trips_201804 <- cb_trips_201804 %>%
  subset(select=c(starttime, usertype))

cb_trips_201805 <- cb_trips_201805 %>%
  subset(select=c(starttime, usertype))

cb_trips_201806 <- cb_trips_201806 %>%
  subset(select=c(starttime, usertype))

cb_trips_201807 <- cb_trips_201807 %>%
  subset(select=c(starttime, usertype))

cb_trips_201808 <- cb_trips_201808 %>%
  subset(select=c(starttime, usertype))

cb_trips_201809 <- cb_trips_201809 %>%
  subset(select=c(starttime, usertype))

cb_trips_201810 <- cb_trips_201810 %>%
  subset(select=c(starttime, usertype))

cb_trips_201811 <- cb_trips_201811 %>%
  subset(select=c(starttime, usertype))

cb_trips_201812 <- cb_trips_201812 %>%
  subset(select=c(starttime, usertype))


cb_trips_201901 <- cb_trips_201901 %>%
  subset(select=c(starttime, usertype))

cb_trips_201902 <- cb_trips_201902 %>%
  subset(select=c(starttime, usertype))

cb_trips_201903 <- cb_trips_201903 %>%
  subset(select=c(starttime, usertype))

cb_trips_201904 <- cb_trips_201904 %>%
  subset(select=c(starttime, usertype))

cb_trips_201905 <- cb_trips_201905 %>%
  subset(select=c(starttime, usertype))

cb_trips_201906 <- cb_trips_201906 %>%
  subset(select=c(starttime, usertype))

cb_trips_201907 <- cb_trips_201907 %>%
  subset(select=c(starttime, usertype))

cb_trips_201908 <- cb_trips_201908 %>%
  subset(select=c(starttime, usertype))

cb_trips_201909 <- cb_trips_201909 %>%
  subset(select=c(starttime, usertype))

cb_trips_201910 <- cb_trips_201910 %>%
  subset(select=c(starttime, usertype))

cb_trips_201911 <- cb_trips_201911 %>%
  subset(select=c(starttime, usertype))

cb_trips_201912 <- cb_trips_201912 %>%
  subset(select=c(starttime, usertype))

cb_trips_all <- rbind(cb_trips_201912,cb_trips_201911,cb_trips_201910,
                      cb_trips_201909,cb_trips_201908,cb_trips_201907,
                      cb_trips_201906,cb_trips_201905,cb_trips_201904,
                      cb_trips_201903,cb_trips_201902,cb_trips_201901,
                      cb_trips_201812,cb_trips_201811,cb_trips_201810,
                      cb_trips_201809,cb_trips_201808,cb_trips_201807,
                      cb_trips_201806,cb_trips_201805,cb_trips_201804,
                      cb_trips_201803,cb_trips_201802,cb_trips_201801)

#cb_trips_all_list <- lapply(cb_trips_all_list, function(i) i %>% select(starttime))

#round start time dates to the nearest day and month for agg purposes
cb_trips_all <- cb_trips_all %>%
  mutate(starttime_day=trunc(starttime, unit='days')) %>%
  mutate(starttime_month=trunc(starttime, unit='months')) %>%
  mutate(week_num=strftime(starttime_day, format='%V')) %>% #average by week to smooth chart
  mutate(year_month_week=strftime(starttime_day, format='%Y-%m-%V'))
  # mutate(year=strftime(starttime_day, format='%Y')) %>%
  # mutate(year_month=strftime(starttime_day, format='%Y-%m'))

# cb_trips_all$year_month <- as.Date(cb_trips_all$year_month, format='%Y-%m')

#filter to non members
cb_trips_non_member <- cb_trips_all %>%
  filter(usertype == 'Customer') %>%
  mutate(non_member = 1)

#filter to members
cb_trips_member <- cb_trips_all %>%
  filter(usertype == 'Subscriber') %>%
  mutate(non_member = 0)

# #agg by day and count all
# cb_trips_all_by_day <- cb_trips_all %>%
#   dplyr::count(starttime_day)
# 
# #agg by day and count non members
# cb_trips_non_member_by_day <- cb_trips_non_member %>%
#   dplyr::count(starttime_day)
# 
# #agg by day and count members
# cb_trips_member_by_day <- cb_trips_member %>%
#   dplyr::count(starttime_day)

#agg by week and count all
cb_trips_all_by_week <- cb_trips_all %>%
  dplyr::count(year_month_week)

#agg by week and count non members
cb_trips_non_member_by_week <- cb_trips_non_member %>%
  dplyr::count(year_month_week)

#agg by week and count members
cb_trips_member_by_week <- cb_trips_member %>%
  dplyr::count(year_month_week)

```

```{r include=FALSE}
#Create dual y-axis chart for visual PTA check

#create df
cb_trips_non_member_by_week_dual <- cb_trips_non_member_by_week %>%
  dplyr::rename(n_cb=n)
indego_trips_non_member_by_week_dual <- indego_trips_non_member_by_week %>%
  dplyr::rename(n_indego=n)

df_dual_chart <- inner_join(cb_trips_non_member_by_week_dual,indego_trips_non_member_by_week_dual, by=c("year_month_week"))

# df_dual_chart$week_num <- as.numeric(df_dual_chart$week_num)
# # df_dual_chart$year <- as.numeric(df_dual_chart$week_num)
# df_dual_chart$year_week <- paste(df_dual_chart$year, df_dual_chart$week_num, sep="")
# # df_dual_chart$year_week <- as.numeric(df_dual_chart$year_week)
# df_dual_chart$year_week <- as.Date(df_dual_chart$year_week)


# df_dual_chart %>% select(-c('year','week_num'))

#scaling coefficient for dual axes
 # coeff <- max(df_dual_chart$n_cb)/max(df_dual_chart$n_indego)

 coeff <- 24 #use this

# chart <- ggplot(df_dual_chart, aes(x=year_month_week, y=n_indego)) +
chart <- ggplot(df_dual_chart, aes(x=factor(year_month_week), y=n_indego, group=1)) +
  # scale_x_continuous(breaks=df_dual_chart$year_week) +
   # geom_smooth(aes(col='blue')) +
  # geom_smooth(aes(y=n_cb/coeff, col='red')) +
  geom_line(aes(), linetype='dashed', col='deepskyblue4') +
  geom_line(aes(y=n_cb/coeff), col='black', linetype='solid') +
  scale_y_continuous(name='Indego Bike Rides (Control)', sec.axis=sec_axis(~.*coeff, name='Citi Bike Rides (Treatment)')) +
  geom_vline(xintercept='2019-05-21', color='red', linewidth=.25) +
  theme_minimal() +
  ggtitle('Non-Member Bike Rides by Week') +
  xlab('Year-Month-Week') +
  theme(
    # axis.title.y = 
    # axis.title.x=element_blank(),
    axis.title.y.left = element_text(color='deepskyblue4'),
    legend.position = 'none',
    plot.title=element_text(hjust = .5, face='bold'),
    axis.text.x = element_text(angle = 75, vjust = 1, hjust=1)
  )
  # scale_fill_discrete(name='Public Bicycle', labels=c('Citi Bikes (Treat)','Indego Bikes (Control)'))

chart
```

```{r include=FALSE}
#dual y-axis chart MEMBERS

options(scipen = 999)

#create df
cb_trips_member_by_week_dual <- cb_trips_member_by_week %>%
  dplyr::rename(n_cb=n)
indego_trips_member_by_week_dual <- indego_trips_member_by_week %>%
  dplyr::rename(n_indego=n)

df_dual_chart_member <- inner_join(cb_trips_member_by_week_dual,indego_trips_member_by_week_dual, by="year_month_week")
# df_dual_chart_member$week_num <- as.numeric(df_dual_chart_member$week_num)


#scaling coefficient for dual axes
coeff_member <- max(df_dual_chart_member$n_cb)/max(df_dual_chart_member$n_indego) #this works well for creating our y-axes scaling coefficient
# coeff_member <- 24

chart_member <- ggplot(df_dual_chart_member, aes(x=factor(year_month_week), y=n_indego, group=1)) + 
  # geom_smooth(aes(col='blue')) +
  # geom_smooth(aes(y=n_cb/coeff, col='red')) +
  geom_line(aes(), linetype='dashed', col='deepskyblue4') +
  geom_line(aes(y=n_cb/coeff_member), linetype='solid', col='black') +
  scale_y_continuous(name='Indego Bike Rides (Control)', sec.axis=sec_axis(~.*coeff_member, name='Citi Bike Rides (Treatment)')) +
  geom_vline(xintercept='2019-05-21', color='red', linewidth=.25) +
  theme_minimal() +
  ggtitle('Member Bike Rides by Week') +
  xlab('Year-Month-Week') + 
  theme(
    axis.title.y.left = element_text(color='deepskyblue4'),
    legend.position = 'none',
    plot.title=element_text(hjust = .5, face='bold'),
    axis.text.x = element_text(angle = 75, vjust = 1, hjust=1)

  )

chart_member
```